# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/patching
- name: Install unattended upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable automitic updates
  ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
  changed_when: false
