#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/patching
- name: Install unattended upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Enable automitic updates
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
